# 目标集群 Broker A 配置
brokerClusterName=SinkCluster
brokerName=tgt-broker-a
brokerId=0
namesrvAddr=namesrv-1:9876;namesrv-2:9876;namesrv-3:9876
listenPort=10911
storePathRootDir=/home/rocketmq/store/tgt-broker-a
storePathCommitLog=/home/rocketmq/store/tgt-broker-a/commitlog
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
deleteWhen=04
fileReservedTime=48
mapedFileSizeCommitLog=104857600
mapedFileSizeConsumeQueue=3000000
